version: "3.8"

services:
  app:
    build: .
    image: desafio-boltons
    volumes:
      - .:/application
    user: "1001:1001"
    networks:
      - desafio

  nginx:
    image: nginx:alpine
    container_name: desafio-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - desafio

  database:
    restart: unless-stopped
    container_name: desafio-database
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      POSTGRES_DB: desafio
      POSTGRES_USER: arquivei
      POSTGRES_PASSWORD: arquivei
      TZ: America/Sao_Paulo
    networks:
      - desafio

networks:
  desafio:
    driver: bridge

volumes:
  data:
    driver: local
