-- Creation of NFes table
CREATE TABLE IF NOT EXISTS n_fes (
  access_key VARCHAR(44) NOT NULL PRIMARY KEY,
  price DECIMAL(13,2) NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITHOUT TIME ZONE
);
